import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { ViewTransitions } from 'next-view-transitions'

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>

      <html lang="en">
        <body
          className={`${inter.className}  antialiased`}
        >
          <div className="pt-4 xl:px-10 2xl:w-4/5 mx-auto">
          <Navbar />

            {children}
          </div>
          <Footer />
        </body>
      </html>
    </ViewTransitions>

  );
}
